name: nombre_proyecto
description: Una breve descripción de tu proyecto

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  material_color_utilities: ^0.5.0
  meta: ^1.10.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
