name: home
description: Una aplicación Flutter básica

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.24.2
  firebase_auth: ^4.5.0
  url_launcher: ^6.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/facebook.png
    - assets/translate.png

